[package]
name = "lib_dmisys"
version = "0.1.0"
edition = "2021"

[dependencies]
get_if_addrs = "0.5.3"
reqwest = { version = "0.12.7", features = ["blocking"] }
sysinfo = "0.31.4"
openssl = { version = "0.10", features = ["vendored"] }