name: Rust Example  CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Build
      working-directory: ./example
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./example
      run: cargo test --verbose
